# Generated by Django 3.1.6 on 2021-04-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardglossary', '0002_auto_20210406_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='ability',
            field=models.TextField(choices=[('None', 'None'), ('Taunt', 'Taunt'), ('Shield', 'Shield'), ('Poison', 'Poison'), ('Frenzy', 'Frenzy'), ('Battlecry', 'Battlecry'), ('Overkill', 'Overkill'), ('Active', 'Active'), ('Windfury', 'Windfury')], default='None'),
        ),
        migrations.AlterField(
            model_name='card',
            name='abilityProperty',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='health',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='strength',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.TextField(choices=[('Human', 'Human'), ('Demon', 'Demon'), ('Animal', 'Animal'), ('Omni', 'Omni'), ('Sorcerer', 'Sorcerer'), ('Demigod', 'Demigod')], default='Human'),
        ),
    ]
